# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FCM-example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FCM-example
# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
# Add the pod for Firebase Cloud Messaging
pod 'Firebase/Messaging'
end
