# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EasyTipView-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EasyTipView-Example
pod 'EasyTipView', '~> 2.1'

end
